# Base image
FROM node:alpine

# Setting up workdir
WORKDIR '/app'

# Copying dependency files
COPY ./package.json .

# Installing dependencies
RUN npm install

# Specifying startup command
CMD ["npm", "start"]