# Base image
FROM node:14-alpine

# Setting up workdir
WORKDIR '/app'

# Copying dependency files
COPY './package.json' '.'
COPY './package-lock.json' '.'

# Installing dependencies
RUN npm install

# Specifying startup command
CMD ["npm", "start"]